nodes:
  - id: reader
    type: FolderImageNode
    folder_path: "./test_images"
    mode: "loop"
    frame_delay: 0.5
    outputs: [model]

  - id: model
    type: ProcessDetInference
    model_config:
      type: YOLOv8
      path: "/Users/bleaf/Desktop/Job/neudc/models/yolov8n.torchscript"
      backend: TorchBackend
      device_id: -1
    outputs: [visualizer]

  - id: visualizer
    type: DrawNode
    outputs: [saver]

  - id: saver
    type: SaveImageNode
    save_dir: "./output_images"
    outputs: []

